app/api/views.py
from flask import (Blueprint, jsonify, request)
from sqlalchemy import func, and_
from app.schema import *
from app.models import (Provinces, Regencies, Districts, Villages,
                        DataODP, DataPDP, DataPositif)

api = Blueprint('api', __name__)


@api.route('/', methods=['GET'])
def index():
    return jsonify("Api Kawal Mudik")


@api.route('/covid', methods=['GET'])
@api.route('/covid/', methods=['GET'])
def Covid():
    return jsonify("Api Kawal Mudik Covid")


@api.route('/tujuan_kecamatan', methods=['GET'])
def CovidTujuanKecamatan():
    q = [(row.id, row.name) for row in Districts.query.all()]
    return jsonify(q)


@api.route('/tujuan_desa', methods=['GET'])
def CovidTujuanDesa():
    district_id = request.args.get('district_id', type=int)
    q = [(row.id, row.name, row.district_id)
         for row in Villages.query.filter_by(district_id=district_id).all()]
    return jsonify(q)


@api.route('/asal_provinsi', methods=['GET'])
def CovidAsalProvinsi():
    q = [(row.id, row.name) for row in Provinces.query.all()]
    return jsonify(q)


@api.route('/asal_kabupaten', methods=['GET'])
def CovidAsalKabupaten():
    province_id = request.args.get('province_id', type=int)
    q = [(row.id, row.name, row.province_id)
         for row in Regencies.query.filter_by(province_id=province_id).all()]
    return jsonify(q)


@api.route('/covid/kabupaten', methods=['GET'])
@api.route('/covid/kabupaten/', methods=['GET'])
def CovidKabupaten():
    kabupaten = DataODP.query.join(DataPDP, DataODP.id != None).join(
        DataPositif, DataODP.id != None).with_entities(
            DataODP.odp_pemantauan, DataODP.odp_selesai,
            DataPDP.pdp_pengawasan, DataPDP.pdp_selesai,
            DataPDP.pdp_meninggal_negatif, DataPositif.positif_dirawat,
            DataPositif.positif_sembuh,
            DataPositif.positif_meninggal).order_by(
                DataODP.created.desc(), DataPDP.created.desc(),
                DataPositif.created.desc()).first()

    return jsonify({
        'odp_pemantauan': kabupaten[0],
        'odp_selesai': kabupaten[1],
        'pdp_pengawasan': kabupaten[2],
        'pdp_selesai': kabupaten[3],
        'pdp_meninggal_negatif': kabupaten[4],
        'positif_dirawat': kabupaten[5],
        'positif_sembuh': kabupaten[6],
        'positif_meninggal': kabupaten[7]
    })

@api.route('/pemudik', methods=['GET', 'POST'])
@api.route('/pemudik/', methods=['GET', 'POST'])
def pemudik():
    desa = Villages.query.outerjoin(CovidPerantau).with_entities(
        Villages.id.label('desa_id'),
        func.count(CovidPerantau.tujuan_desa).label('pemudik')).group_by(
            Villages.id).all()
    result = covid_perantau_jumlah_per_desa_schema.dump(desa, many=True)
    return jsonify(result)

app/covid19/__init__.py
from app.covid19.views import covid19  # noqa

app/covid19/views.py
from flask import (Blueprint, render_template, flash, redirect, url_for, g,
                   request, current_app)
from flask_rq import get_queue
from flask_babel import _
from app.covid19.forms import (CovidPerantauForm, CovidPerantauLuarNegeriForm,
                               ScreeningForm, DeteksiSakitForm, SearchForm)
from app.models import (CovidPerantau, CovidDeteksiMandiri, DeteksiSakit,
                        Posko, RumahSakit, Puskesmas, DataODP, DataPDP,
                        DataPositif)
from app import db
from app.email import send_email
from config import Config
from datetime import date

covid19 = Blueprint('covid19', __name__)


@covid19.before_request
def before_request():
    db.session.commit()
    g.search_form = SearchForm()


@covid19.route('/lapor-mudik', methods=['GET', 'POST'])
def LaporMudik():
    """Tambah Lapor Mudik Masuk Desa"""
    title = "Input Data Pemudik Dalam Negeri"
    description = "Kawal Mudik"
    form = CovidPerantauForm()
    if form.validate_on_submit():
        q = CovidPerantau(first_name=form.first_name.data,
                          last_name=form.last_name.data,
                          nik=form.nik.data,
                          tgl_lahir=form.tgl_lahir.data,
                          jk=form.jk.data,
                          shdk=form.shdk.data,
                          jml_ak_dan_pemudik=form.jml_ak_dan_pemudik.data,
                          tujuan_kecamatan=form.tujuan_kecamatan.data,
                          tujuan_desa=form.tujuan_desa.data,
                          alamat=form.alamat.data,
                          email=form.email.data,
                          telp=form.telp.data,
                          asal_provinsi=form.asal_provinsi.data,
                          asal_kabupaten=form.asal_kabupaten.data,
                          alasan_mudik=form.alasan_mudik.data,
                          alasan_mudik_lainnya=form.alasan_mudik_lainnya.data,
                          tgl_mudik=form.tgl_mudik.data,
                          demam=form.demam.data,
                          batuk_pilek=form.batuk_pilek.data,
                          sakit_tenggorokan=form.sakit_tenggorokan.data,
                          sesak_napas=form.sesak_napas.data)
        db.session.add(q)
        print(q)
        db.session.commit()
        if q.email == '':
            flash('Terima kasih sudah membuat laporan !!', 'success')
            return redirect(url_for('covid19.LaporMudik'))
        else:
            get_queue().enqueue(send_email,
                                recipient=q.email,
                                subject='Laporan Mudik Diterima',
                                template='account/email/lapor_mudik',
                                q=q)
            flash(
                'Laporan Berhasil, Pemberitahuan akan di \
                        kirimkan melalui email {}.'.format(q.email), 'success')
            return redirect(url_for('covid19.LaporMudik'))
    return render_template('covid19/index.html',
                           form=form,
                           title=title,
                           description=description)


@covid19.route('/lapor-mudik/luar-negeri', methods=['GET', 'POST'])
def LaporMudikLuarNegeri():
    """Tambah Lapor Mudik Masuk Desa dari Luar Negeri"""
    title = "Input Data Pemudik Luar Negeri"
    description = "Kawal Mudik"
    form = CovidPerantauLuarNegeriForm()
    if form.validate_on_submit():
        q = CovidPerantau(first_name=form.first_name.data,
                          last_name=form.last_name.data,
                          nik=form.nik.data,
                          tgl_lahir=form.tgl_lahir.data,
                          jk=form.jk.data,
                          shdk=form.shdk.data,
                          jml_ak_dan_pemudik=form.jml_ak_dan_pemudik.data,
                          tujuan_kecamatan=form.tujuan_kecamatan.data,
                          tujuan_desa=form.tujuan_desa.data,
                          alamat=form.alamat.data,
                          email=form.email.data,
                          telp=form.telp.data,
                          asal_negara=form.asal_negara.data,
                          alasan_mudik=form.alasan_mudik.data,
                          alasan_mudik_lainnya=form.alasan_mudik_lainnya.data,
                          tgl_mudik=form.tgl_mudik.data,
                          demam=form.demam.data,
                          batuk_pilek=form.batuk_pilek.data,
                          sakit_tenggorokan=form.sakit_tenggorokan.data,
                          sesak_napas=form.sesak_napas.data)
        db.session.add(q)
        db.session.commit()
        if q.email == '':
            flash('Terima kasih sudah membuat laporan !!', 'success')
            return redirect(url_for('covid19.LaporMudik'))
        else:
            get_queue().enqueue(send_email,
                                recipient=q.email,
                                subject='Laporan Mudik Diterima',
                                template='account/email/lapor_mudik',
                                q=q)
            flash(
                'Laporan Berhasil, Pemberitahuan akan di \
                        kirimkan melalui email {}.'.format(q.email), 'success')
            return redirect(url_for('covid19.LaporMudik'))
    return render_template('covid19/index.html',
                           form=form,
                           title=title,
                           description=description)


@covid19.route('/screening', methods=['GET', 'POST'])
def Screening():
    """Tambah Data Screening atau Deteksi Mandiri"""
    title = "Deteksi Mandiri"
    description = "Kawal Mudik"
    form = ScreeningForm()
    if form.validate_on_submit():
        q = CovidDeteksiMandiri(
            demam=form.demam.data,
            batuk_pilek=form.batuk_pilek.data,
            sakit_tenggorokan=form.sakit_tenggorokan.data,
            sesak_napas=form.sesak_napas.data,
            penyakit_14hari=form.penyakit_14hari.data,
            riwayat_kontak_penderita=form.riwayat_kontak_penderita.data,
            riwayat_prjalan_luar=form.riwayat_prjalan_luar.data,
            riwayat_perjalanan_lokal=form.riwayat_perjalanan_lokal.data)
        print(form.demam.data)
        if (form.demam.data or form.batuk_pilek.data
                or form.sakit_tenggorokan.data or form.sesak_napas.data or
                form.penyakit_14hari.data or form.riwayat_kontak_penderita.data
                or form.riwayat_prjalan_luar.data
                or form.riwayat_perjalanan_lokal.data) is True:
            db.session.add(q)
            db.session.commit()
            return redirect(url_for('covid19.ScreeningSakit'))
        else:
            return redirect(url_for('covid19.ScreeningSehat'))
    return render_template('covid19/screening.html',
                           title=title,
                           form=form,
                           description=description)


@covid19.route('/screening-sehat', methods=['GET', 'POST'])
def ScreeningSehat():
    """Informasi Deteksi Mandiri Sehat"""
    title = "Status Sehat"
    description = "Kawal Mudik"
    return render_template('covid19/screening_sehat.html',
                           title=title,
                           description=description)


@covid19.route('/screening-sakit', methods=['GET', 'POST'])
def ScreeningSakit():
    """Tambah Data Hasil Screening Sakit"""
    title = "Lapor Saya Sakit"
    description = "Kawal Mudik"
    form = DeteksiSakitForm()
    if form.validate_on_submit():
        q = DeteksiSakit(first_name=form.first_name.data,
                         last_name=form.last_name.data,
                         kecamatan=form.kecamatan.data,
                         desa=form.desa.data,
                         alamat=form.alamat.data,
                         email=form.email.data,
                         telp=form.telp.data)
        db.session.add(q)
        db.session.commit()
        get_queue().enqueue(send_email,
                            recipient=Config.ADMIN_EMAIL,
                            subject='Pemberitahuan Laporan Masyarakat Sakit',
                            template='account/email/lapor_admin_sakit')
        get_queue().enqueue(send_email,
                            recipient=q.email,
                            subject='Laporan Sakit Diterima',
                            template='account/email/lapor_sakit',
                            q=q)
        flash(
            'Laporan Berhasil, Pemberitahuan akan di \
                    kirimkan melalui email {}.'.format(q.email), 'success')
        return redirect(url_for('covid19.LaporMudik'))
        flash('Data berhasil di tambahkan', 'success')
    return render_template('covid19/screening_sakit.html',
                           form=form,
                           title=title,
                           description=description)


@covid19.route('/fasilitas-kesehatan', methods=['GET', 'POST'])
def FasilitasKesehatan():
    """Fasilitas Kesehatan Posko, Rumah Sakit dan Puskesmas"""
    title = "Fasilitas Kesehatan"
    description = "Kawal Mudik"
    posko = Posko.query.all()
    rs = RumahSakit.query.all()
    puskesmas = Puskesmas.query.all()
    return render_template('covid19/fasilitas_kesehatan.html',
                           title=title,
                           description=description,
                           posko=posko,
                           rs=rs,
                           puskesmas=puskesmas)


"""Statistik Covid-19 Kabupaten"""
@covid19.route('/publik/statistik-corona')
def StatistikCoronaKabupaten():
    odp = DataODP.query.order_by(DataODP.id.desc()).first()
    pdp = DataPDP.query.order_by(DataPDP.id.desc()).first()
    positif = DataPositif.query.order_by(DataPositif.id.desc()).first()
    return render_template('covid19/embed/statistik_kabupaten.html',
                           odp=odp,
                           pdp=pdp,

app/templates/covid19/fasilitas_kesehatan.html
{% extends "core/homepage/core_template.html" %}
{% block content %}
{% include 'core/homepage/core_navbar.html' %}

<div class="wrapper">

    <div class="container">

        <!-- Start page tittle and breadcrumb -->
        {% include 'homepage/breadcrumb.html' %}
        <!-- end page title and breadcrumb -->
            <div class="container">               
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box table-responsive">
                            <h4 class="m-t-0 header-title"><b>{{_('Data Posko Penanganan Covid-19')}}</b></h4>
                            <p class="text-muted font-13 m-b-30">
                                {{ title }}
                            </p>
                            <!--start table-->
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>{{_('No')}}</th>
                                        <th>{{_('Posko')}}</th>
                                        <th>{{_('Alamat')}}</th>
                                        <th>{{_('Telp')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for u in posko %}
                                    <tr>
                                        <td>{{ loop.index }}</td>
                                        <td>{{ u.name }}</td>
                                        <td>{{ u.alamat }}</td>
                                        <td>{{ u.telp }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <!--end table-->
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box table-responsive">
                            <h4 class="m-t-0 header-title"><b>{{_('Rumah Sakit Penanganan Covid-19')}}</b></h4>
                            <p class="text-muted font-13 m-b-30">
                                {{ title }}
                            </p>
                            <!--start table-->
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>{{_('No')}}</th>
                                        <th>{{_('Nama Rumah Sakit')}}</th>
                                        <th>{{_('Alamat')}}</th>
                                        <th>{{_('Telp')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for u in rs %}
                                    <tr>
                                        <td>{{ loop.index }}</td>
                                        <td>{{ u.name }}</td>
                                        <td>{{ u.alamat }}</td>
                                        <td>{{ u.telp }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <!--end table-->
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box table-responsive">
                            <h4 class="m-t-0 header-title"><b>{{_('Puskesmas Penanganan Covid-19')}}</b></h4>
                            <p class="text-muted font-13 m-b-30">
                                {{ title }}
                            </p>
                            <!--start table-->
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>{{_('No')}}</th>
                                        <th>{{_('Nama Puskesmas')}}</th>
                                        <th>{{_('Alamat')}}</th>
                                        <th>{{_('Telp')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for u in puskesmas %}
                                    <tr>
                                        <td>{{ loop.index }}</td>
                                        <td>{{ u.name }}</td>
                                        <td>{{ u.alamat }}</td>
                                        <td>{{ u.telp }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <!--end table-->
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <!-- end row -->
    <!--Footer-->
    {% include 'core/homepage/core_footer.html' %}
    <!--End Footer-->
</div>
</div>
{% endblock %}

app/templates/covid19/screening_sakit.html
{% extends "core/homepage/core_template.html" %}
{% block customcss %}
<!--Date Picker -->
<link href="{{ url_for('static', filename='plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css">

<!-- Plugins css-->
<link href="{{ url_for('static', filename='plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css') }}" rel="stylesheet" type="text/css">
<link href="{{ url_for('static', filename='plugins/multiselect/css/multi-select.css') }}" rel="stylesheet" type="text/css">
<link href="{{ url_for('static', filename='plugins/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ url_for('static', filename='plugins/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ url_for('static', filename='plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css') }}" rel="stylesheet" type="text/css">

<style type="text/css">
.g-recaptcha{
transform:scale(0.77);
-webkit-transform:scale(0.77);
transform-origin:0 0;
-webkit-transform-origin:0 0;
}
</style>
{% endblock %}
{% block content %}
{% include 'core/homepage/core_navbar.html' %}

<div class="wrapper">

    <div class="container">

        <!-- Start page tittle and breadcrumb -->
        {% include 'homepage/breadcrumb.html' %}
        <!-- end page title and breadcrumb -->
        {% with informations = get_flashed_messages(category_filter=["success"]) %}
        {% if informations %}
        <div class="alert alert-icon alert-info alert-dismissible fade in" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <i class="mdi mdi-information-outline"></i>
          {% for msg in informations %}
          <strong>{{ msg }}</strong>
          {% endfor -%}
        </div>
        {% endif %}
        {% endwith %}
        
        <!-- Start Data Input -->
              <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="card-box">
                        <h4 class="header-title m-t-0">{{ title }}</h4>
                        <form method="POST" action="{{url_for('covid19.ScreeningSakit')}}">
                           {{ form.hidden_tag() }}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="p-20">
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-6 m-b-10">
                                                    {{ form.first_name.label }}<span class="text-danger">*</span>
                                                    {{ form.first_name(class="form-control") }}
                                                    {% for error in form.first_name.errors %}
                                                    <span style="color: red;">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                                <div class="col-sm-6 m-b-10">
                                                    {{ form.last_name.label }}<span class="text-danger">*</span>
                                                    {{ form.last_name(class="form-control") }}
                                                    {% for error in form.last_name.errors %}
                                                    <span style="color: red;">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-6 m-b-10">
                                                    {{ form.kecamatan.label }}<span class="text-danger">*</span>
                                                    {{ form.kecamatan(class="form-control") }}
                                                    {% for error in form.kecamatan.errors %}
                                                    <span style="color: red;">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                                <div class="col-sm-6 m-b-10">
                                                    {{ form.desa.label }}<span class="text-danger">*</span>
                                                    {{ form.desa(class="form-control") }}
                                                    {% for error in form.desa.errors %}
                                                    <span style="color: red;">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                                
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-12 m-b-10">
                                                    {{ form.alamat.label }}<span class="text-danger">*</span>
                                                    {{ form.alamat(class="form-control") }}
                                                    {% for error in form.alamat.errors %}
                                                    <span style="color: red;">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-12 m-b-10">
                                                    {{ form.email.label }}<span class="text-danger">*</span>
                                                    {{ form.email(class="form-control") }}
                                                    {% for error in form.email.errors %}
                                                    <span style="color: red;">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-12 m-b-10">
                                                    {{ form.telp.label }}<span class="text-danger">*</span>
                                                    {{ form.telp(class="form-control") }}
                                                    {% for error in form.telp.errors %}
                                                    <span style="color: red;">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-12 m-b-10">
                                                    {{ form.recaptcha }}
                                                </div>
                                            </div>
                                        </div>
                                        

                                    </div>
                                    <!-- end class p-20 -->
                                </div> <!-- end col -->


                            </div> <!-- end row -->

                            <div class="text-center">
                                <button type="submit" class="btn btn-success waves-effect waves-light">{{_('Lapor Sekarang')}}</button>
                            </div>
                        </form>
                        <!-- end form -->

                    </div> <!-- end card-box -->
                </div> <!-- end col -->
            </div>
            <!-- end row -->
        <!-- end Data Input -->

    </div>
    <!-- end row -->
    <!--Footer-->
    {% include 'core/homepage/core_footer.html' %}
    <!--End Footer-->
</div>
</div>
{% endblock %}
{% block customjs %}

<!--Datepicker-->
<script src="{{ url_for('static', filename='plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>

<script charset="utf-8" type="text/javascript">

$(function() {

    // jQuery selection for the 2 select boxes
    var dropdown = {
        district_id: $('#lokasi_kecamatan'),
        village_id: $('#lokasi_desa')
    };

    getKecamatanTujuan();
    dropdown.village_id.attr('disabled', 'disabled');

    // function to call XHR kelembagaan dropdown
    function getKecamatanTujuan() {
        dropdown.district_id.empty();
        dropdown.district_id.append(
                    $('<option>', {
                        value: '',
                        text: "--- Pilih Lokasi Kecamatan Saya ---"
                    })
                );
        $.getJSON("{{ url_for('api.CovidTujuanKecamatan') }}", function(data) {
            data.forEach(function(item) {
                dropdown.district_id.append(
                    $('<option>', {
                        value: item[0],
                        text: item[1]
                    })
                );
            });
        });
    }


    // call to update on load
    updateDesaTujuan();

    // function to call XHR and update jabatan_id dropdown
    function updateDesaTujuan() {
        var send = {
            district_id: dropdown.district_id.val()
        };
        dropdown.village_id.attr('disabled', 'disabled');
        dropdown.village_id.empty();
        dropdown.village_id.append(
            $('<option>', {
                value: '',
                text: '-- Pilih Lokasi Desa Saya --'
            })
        );

        $.getJSON("{{ url_for('api.CovidTujuanDesa') }}", send, function(data) {
            data.forEach(function(item) {
                dropdown.village_id.append(
                    $('<option>', {
                        value: item[0],
                        text: item[1]
                    })
                );
            });
            dropdown.village_id.removeAttr('disabled');
        });
    }

    // event listener to state dropdown change
    dropdown.district_id.on('change', function() {
        updateDesaTujuan();
    });

});

</script>

{% endblock %}