app/account/views.py
from flask import (Blueprint, flash, redirect, render_template, request,
                   url_for)
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)
from flask_rq import get_queue

from app import db
from app.account.forms import (ChangeEmailForm, ChangePasswordForm,
                               CreatePasswordForm, LoginForm,
                               RequestResetPasswordForm, ResetPasswordForm,
                               RequestAccount)
from app.email import send_email
from app.models import User
from config import Config

account = Blueprint('account', __name__)


@account.route('/login', methods=['GET', 'POST'])
def login():
    """Log in an existing user."""
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    else:
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.password_hash is not None and \
                    user.verify_password(form.password.data):
                login_user(user, user.login_now())
                flash('Selamat Datang', 'success_login')
                return redirect(
                    request.args.get('next') or url_for('main.index'))
            else:
                flash('Invalid email or password.', 'error')
    return render_template('account/login.html', form=form)


@account.route('/request-account', methods=['GET', 'POST'])
def AccountRequest():
    """Respond to existing user's request to reset their password."""
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    form = RequestAccount()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash(
                'Alamat email {}. tidak diperbolehkan mendaftar, \
                    Gunakan email resmi desa !!'.format(form.email.data),
                'message-error')
            return redirect(url_for('account.AccountRequest'))
        else:
            if user.confirmed is True:
                flash(
                    'Alamat email {}. sudah aktif'.format(form.email.data),
                    'message-error')
                return redirect(url_for('account.AccountRequest'))
            else:
                confirm_link = url_for('account.login', _external=True)
                get_queue().enqueue(
                    send_email,
                    recipient=Config.ADMIN_EMAIL,
                    subject='Pemberitahuan Pengajuan Akun',
                    template='account/email/admin_registration',
                    user=user,
                    confirm_link=confirm_link)
                get_queue().enqueue(
                    send_email,
                    recipient=user.email,
                    subject='Pengajuan Akun Berhasil',
                    template='account/email/user_registration',
                    user=user)
            flash(
                'Terima kasih sudah melakukan pengajuan, aktivasi akan kami \
                    dikirim melalui email {}.'.format(form.email.data),
                'message-success')
            return redirect(url_for('account.login'))
    return render_template('account/request_account.html', form=form)


@account.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.index'))


@account.route('/manage', methods=['GET', 'POST'])
@account.route('/manage/info', methods=['GET', 'POST'])
@login_required
def manage():
    """Display a user's account information."""
    return render_template('account/manage.html', user=current_user, form=None)


@account.route('/reset-password', methods=['GET', 'POST'])
def reset_password_request():
    """Respond to existing user's request to reset their password."""
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    form = RequestResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('Alamat email {}. belum terdaftar'.format(form.email.data),
                  'message-error')
            return redirect(url_for('account.reset_password_request'))
        else:
            token = user.generate_password_reset_token()
            reset_link = url_for('account.reset_password',
                                 token=token,
                                 _external=True)
            get_queue().enqueue(send_email,
                                recipient=user.email,
                                subject='Reset Your Password',
                                template='account/email/reset_password',
                                user=user,
                                reset_link=reset_link,
                                next=request.args.get('next'))
        flash(
            'Tautan pengaturan ulang kata sandi telah dikirim ke email {}.'.
            format(form.email.data), 'message-success')
        return redirect(url_for('account.login'))
    return render_template('account/reset_password.html', form=form)


@account.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    """Reset an existing user's password."""
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('Invalid email address.', 'message-error')
            return redirect(
                url_for(
                    'account.reset_password, token=token, , _external=True'))
        if user.reset_password(token, form.new_password.data):
            flash('Kata sandi Anda telah diperbarui.', 'message-success')
            return redirect(url_for('account.login'))
        else:
            flash(
                'Tautan pengaturan ulang kata sandi tidak valid atau \
                 kedaluwarsa.', 'message-error')
            return redirect(url_for('account.reset_password_request'))
    return render_template('account/new_password.html', form=form)


@account.route('/manage/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    """Change an existing user's password."""
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.new_password.data
            db.session.add(current_user)
            db.session.commit()
            flash('Your password has been updated.', 'form-success')
            return redirect(url_for('main.index'))
        else:
            flash('Original password is invalid.', 'form-error')
    return render_template('account/manage.html', form=form)


@account.route('/manage/change-email', methods=['GET', 'POST'])
@login_required
def change_email_request():
    """Respond to existing user's request to change their email."""
    form = ChangeEmailForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            new_email = form.email.data
            token = current_user.generate_email_change_token(new_email)
            change_email_link = url_for('account.change_email',
                                        token=token,
                                        _external=True)
            get_queue().enqueue(
                send_email,
                recipient=new_email,
                subject='Confirm Your New Email',
                template='account/email/change_email',
                # current_user is a LocalProxy, we want the underlying user
                # object
                user=current_user._get_current_object(),
                change_email_link=change_email_link)
            flash('A confirmation link has been sent to {}.'.format(new_email),
                  'warning')
            return redirect(url_for('main.index'))
        else:
            flash('Invalid email or password.', 'form-error')
    return render_template('account/manage.html', form=form)


@account.route('/manage/change-email/<token>', methods=['GET', 'POST'])
@login_required
def change_email(token):
    """Change existing user's email with provided token."""
    if current_user.change_email(token):
        flash('Your email address has been updated.', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'error')
    return redirect(url_for('main.index'))


@account.route('/confirm-account')
@login_required
def confirm_request():
    """Respond to new user's request to confirm their account."""
    token = current_user.generate_confirmation_token()
    confirm_link = url_for('account.confirm', token=token, _external=True)
    get_queue().enqueue(
        send_email,
        recipient=current_user.email,
        subject='Confirm Your Account',
        template='account/email/confirm',
        # current_user is a LocalProxy, we want the underlying user object
        user=current_user._get_current_object(),
        confirm_link=confirm_link)
    flash(
        'A new confirmation link has been sent to {}.'.format(
            current_user.email), 'warning')
    return redirect(url_for('main.index'))


@account.route('/confirm-account/<int:user_id>/<token>')
@login_required
def confirm(user_id, token):
    """Confirm new user's account with provided token."""
    user = User.query.get(user_id)
    if user.confirmed:
        return redirect(url_for('main.index'))
    if user.confirm_account(token):
        print(user)
        print(current_user)
        flash('Your account has been confirmed.', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'error')

app/main/views.py
from flask import Blueprint, render_template
from sqlalchemy import func, and_
from app import cache
from app.models import (DataODP, DataPDP, DataPositif, CovidPerantau,
                        DeteksiSakit, Districts)
from datetime import date

main = Blueprint('main', __name__)


@main.route('/')
@cache.cached(timeout=60)
def index():
    today = date.today()
    odp = DataODP.query.order_by(DataODP.id.desc()).first()
    pdp = DataPDP.query.order_by(DataPDP.id.desc()).first()
    positif = DataPositif.query.order_by(DataPositif.id.desc()).first()
    mudik_today = CovidPerantau.query.filter_by(tgl_mudik=today).count()
    news_pemudik = CovidPerantau.query.order_by(
        CovidPerantau.id.desc()).limit(5).all()
    news_laporsakit = DeteksiSakit.query.order_by(
        DeteksiSakit.id.desc()).limit(5).all()
    daily_pemudik = CovidPerantau.query.with_entities(
        CovidPerantau.tgl_mudik,
        func.count(CovidPerantau.first_name).label('count')).group_by(
            CovidPerantau.tgl_mudik).filter(
                and_(CovidPerantau.tgl_mudik <= today,
                     CovidPerantau.tgl_mudik >= '2020-01-01')).order_by(
                         CovidPerantau.tgl_mudik.asc()).all()
    pemudik_kecamatan = Districts.query.outerjoin(CovidPerantau).with_entities(
        Districts.id, Districts.name,
        func.count(CovidPerantau.first_name).label('total')).group_by(
            Districts.id, Districts.name).all()
    return render_template('homepage/index.html',
                           odp=odp,
                           pdp=pdp,
                           positif=positif,
                           mudik_today=mudik_today,
                           news_pemudik=news_pemudik,
                           news_laporsakit=news_laporsakit,
                           daily_pemudik=daily_pemudik,
                           pemudik_kecamatan=pemudik_kecamatan)


@main.route('/mudik')
def mudik():
    today = date.today()
    odp = DataODP.query.order_by(DataODP.id.desc()).first()
    pdp = DataPDP.query.order_by(DataPDP.id.desc()).first()
    positif = DataPositif.query.order_by(DataPositif.id.desc()).first()
    mudik_today = CovidPerantau.query.filter_by(tgl_mudik=today).count()
    news_pemudik = CovidPerantau.query.order_by(
        CovidPerantau.id.desc()).limit(5).all()
    news_laporsakit = DeteksiSakit.query.order_by(
        DeteksiSakit.id.desc()).limit(5).all()
    daily_pemudik = CovidPerantau.query.with_entities(
        CovidPerantau.tgl_mudik,
        func.count(CovidPerantau.first_name).label('count')).group_by(
            CovidPerantau.tgl_mudik).filter(
                and_(CovidPerantau.tgl_mudik <= today,
                     CovidPerantau.tgl_mudik >= '2020-01-01')).order_by(
                         CovidPerantau.tgl_mudik.asc()).all()
    pemudik_kecamatan = Districts.query.outerjoin(CovidPerantau).with_entities(
        Districts.id, Districts.name,
        func.count(CovidPerantau.first_name).label('total')).group_by(
            Districts.id, Districts.name).all()
    return render_template('homepage/index.html',
                           odp=odp,
                           pdp=pdp,
                           positif=positif,
                           mudik_today=mudik_today,
                           news_pemudik=news_pemudik,
                           news_laporsakit=news_laporsakit,
                           daily_pemudik=daily_pemudik,
                           pemudik_kecamatan=pemudik_kecamatan)

app/templates/core/homepage/core_footer.html
<!-- Footer -->
<footer class="footer text-right">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    {{('Made with ')}}<i class="mdi mdi-heart"></i>
                    | {{('2020 © Lapor Mudik Anakdesa -')}} <a href="https://kodenusantara.co.id" target="_blank">{{('Kode Nusantara')}}</a> X <a href="https://twitter.com/anakdesaid" target="_blank">{{('Anakdesa ID')}}</a>                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->

app/templates/core/homepage/core_navbar.html
<!-- Navigation Bar-->
<header id="topnav">
    <div class="topbar-main">
        <div class="container">
            <!-- Logo container-->
            <div class="logo">
                <a href="{{ url_for('main.index') }}" class="logo">
                    <img src="{{ resized_img_src('dist/img/kawal-logo.png', width=40) }}" alt="logo">
                    {% block page_title %}{{ config.APP_NAME }}{% endblock %}
                </a>
            </div>
            <!-- End Logo container-->
                <!--Login Button-->
                <ul class="nav navbar-nav navbar-right pull-right">
                    <li class="navbar-c-items" style="padding-top: 5px">
                        <button onclick="myFunction()" type="button" class="btn btn-primary btn-sm w-sm waves-effect m-t-10 waves-light">
                        {% if not (current_user.is_authenticated) %} {{_('Login')}} {% else %} {{_('Logout')}} {% endif %}</button>
                    </li>                   
                </ul>
                <!--End Login Button-->
                <script>
                    function myFunction() {
                        location.replace("{% if not (current_user.is_authenticated) %} {{ url_for('account.login') }} {% else %} {{ url_for('account.logout') }} {% endif %}")
                    }
                </script>
                
                <div class="menu-item">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </div>
            </div>
            <!-- end menu-extras -->
        </div> 
        <!-- end container -->
    </div>
    <!-- end topbar-main -->

    <!--Secondari Navbar-->
    <div class="navbar-custom">
        <div class="container">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu">
                    <li>
                        <a href="{{ url_for('main.index') }}"><i class="mdi mdi-home-map-marker"></i>{{_('Beranda')}}</a>
                    </li>
                    <li class="has-submenu">
                        <a href="#"><i class="mdi mdi-car"></i>{{_('Lapor Mudik')}}</a>
                        <ul class="submenu">
                            <li>
                                <a href="{{ url_for('covid19.LaporMudik') }}"><i class="mdi mdi-car"></i>{{_('  Dari Dalam Negeri')}}</a>
                            </li>
                            <li>
                                <a href="{{ url_for('covid19.LaporMudikLuarNegeri') }}"><i class="mdi mdi-airplane"></i>{{_('  Dari Luar Negeri')}}</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{ url_for('covid19.Screening') }}"><i class="mdi mdi-account-search"></i>{{_('Deteksi Mandiri')}}</a>
                    </li>
                    <li>
                        <a href="{{ url_for('covid19.FasilitasKesehatan') }}"><i class="mdi mdi-hospital"></i>{{_('Fasilitas Kesehatan')}}</a>
                    </li>
                    <li class="has-submenu">
                        <a href="#"><i class="mdi mdi-information-outline"></i>{{_('Info Corona Lainnya')}}</a>
                        <ul class="submenu">
                            <li><a href="https://infocorona.pemalangkab.go.id">{{_('Info Corona Pemalang')}}</a></li>
                            <li><a href="https://corona.jatengprov.go.id">{{_('Info Corona Jawa Tengah')}}</a></li>
                            <li><a href="https://www.covid19.go.id/">{{_('Info Corona Nasional')}}</a></li>
                            <li><a href="https://kawalcovid19.id/">{{_('Kawal Covid19')}}</a></li>
                            <li><a href="https://google.com/covid19-map/">{{_('Covid19 Internasional')}}</a></li>
                        </ul>
                    </li>

                    {% if current_user.is_authenticated %}
                    <li>
                        <a href="{{url_for(current_user.role.index + ".index")}}"><i class="mdi mdi-file-document"></i>
                        {{'Dashboard '+ current_user.role.name}}
                        </a>
                    </li>
                    {% endif %}
                    


                </ul>
                <!-- End navigation menu -->
            </div> <!-- end #navigation -->
        </div> <!-- end container -->
    </div> <!-- end navbar-custom -->
</header>
<!-- End Navigation Bar-->

app/templates/core/homepage/core_template.html
<!DOCTYPE html>
<html lang="en">

<head>{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{('Kawal Mudik Anakdesa 2020')}}">
    <meta name="author" content="{{('Puspindes')}}">
    <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='corona/assets/images/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='corona/assets/images/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='corona/assets/images/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='corona/assets/images/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='corona/assets/images/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='corona/assets/images/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='corona/assets/images/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='corona/assets/images/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='corona/assets/images/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='corona/assets/images/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='corona/assets/images/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='corona/assets/images/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='corona/assets/images/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='corona/assets/images/manifest.json') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ url_for('static', filename='corona/assets/images/ms-icon-144x144.png') }}">
    <meta name="theme-color" content="#ffffff">

    <!-- Title -->
    <title>{% block title %} {% if title %}{{'Kawal Mudik - '}} {{ title }} {% else %} {{ config.APP_NAME }} {% endif %} {% endblock %}</title>

    {% block customcss %} {% endblock %}

    <!-- App css -->
    <link href="{{ url_for('static', filename='corona/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='corona/assets/css/core.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='corona/assets/css/components.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='corona/assets/css/icons.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='corona/assets/css/pages.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='corona/assets/css/menu.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='corona/assets/css/responsive.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='plugins/switchery/switchery.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='corona/assets/css/sweetalert.css') }}" rel="stylesheet" type="text/css">
    <!-- End App css-->
    <script src="{{ url_for('static', filename='corona/assets/js/modernizr.min.js')}}"></script>

    {% if config.GOOGLE_ANALYTICS_ID %}
    <!-- Google Analytics -->
    <script type="text/javascript">
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', '{{ config.GOOGLE_ANALYTICS_ID }}', 'auto');
        ga('send', 'pageview');
    </script>
    {% endif %} {% endblock %}</head>

{% block content %}
<!-- ISI KONTEN ANDA LIK -->
{% endblock %} {% block javascript %}
<script>
    var resizefunc = [];
</script>

<!-- Jquery Lik -->
<script src="{{ url_for('static', filename='corona/assets/js/jquery.min.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/detect.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/fastclick.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/jquery.blockUI.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/waves.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/jquery.slimscroll.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/jquery.scrollTo.min.js')}}"></script>
<script src="{{ url_for('static', filename='plugins/switchery/switchery.min.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/sweetalert.min.js')}}"></script>

{% block customjs %} {% endblock %}

<!-- App js -->
<script src="{{ url_for('static', filename='corona/assets/js/jquery.core.js')}}"></script>
<script src="{{ url_for('static', filename='corona/assets/js/jquery.app.js')}}"></script>
{% endblock %}

</body>

</html>