app/desa/views.py
from flask import (Blueprint, render_template, url_for, flash, redirect)
from flask_login import login_required
from app.decorators import required_roles
from flask_login import (current_user)
from flask_rq import get_queue

from datetime import datetime
from io import TextIOWrapper
import csv
from sqlalchemy import exc

from app.models import (CovidPerantau, DeteksiSakit, DataODP, DataPDP,
                        DataPositif, Country, Provinces, Regencies)
from app.desa.forms import (EmbedCodeKab, EmbedCodePemudik,
                            EmbedCodeOrangSakit, EmbedCodeSearchPemudik,
                            ImportPemudikForm)
from app.covid19.forms import CovidPerantauForm, CovidPerantauLuarNegeriForm

from app.email import send_email
from app import db

desa = Blueprint('desa', __name__)


@desa.route('/')
@login_required
@required_roles('Desa')
def index():
    today = datetime.today()
    odp = DataODP.query.order_by(DataODP.id.desc()).first()
    pdp = DataPDP.query.order_by(DataPDP.id.desc()).first()
    positif = DataPositif.query.order_by(DataPositif.id.desc()).first()
    mudik_today = CovidPerantau.query.filter_by(
        tgl_mudik=today, tujuan_desa=current_user.village_id).count()
    news_pemudik = CovidPerantau.query.filter_by(
        tujuan_desa=current_user.village_id).order_by(
            CovidPerantau.id.desc()).limit(5).all()
    news_laporsakit = DeteksiSakit.query.filter_by(
        desa=current_user.village_id).order_by(
            DeteksiSakit.id.desc()).limit(5).all()
    total_perantau = CovidPerantau.query.filter_by(
        tujuan_desa=current_user.village_id).count()
    total_perantau_pulang = CovidPerantau.query.filter_by(
        tujuan_desa=current_user.village_id, confirmed=True).count()
    total_sakit = DeteksiSakit.query.filter_by(
        desa=current_user.village_id).count()
    total_sakit_sudah_ditangani = DeteksiSakit.query.filter_by(
        desa=current_user.village_id, confirmed=True).count()
    return render_template(
        'covid19/desa/index.html',
        odp=odp,
        pdp=pdp,
        positif=positif,
        mudik_today=mudik_today,
        news_pemudik=news_pemudik,
        news_laporsakit=news_laporsakit,
        total_perantau=total_perantau,
        total_perantau_pulang=total_perantau_pulang,
        total_sakit=total_sakit,
        total_sakit_sudah_ditangani=total_sakit_sudah_ditangani)


"""Covid19"""
@desa.route('/perantau/view/data')
@login_required
@required_roles('Desa')
def PerantauDataView():
    """View all Data Perantau mau mudik"""
    title = "Data Perantau"
    page = "View Data Perantau"
    description = "Desa vs Corona"
    data = CovidPerantau.query.order_by(CovidPerantau.id.desc()).filter_by(
        tujuan_desa=current_user.village_id).all()
    return render_template('covid19/data/index.html',
                           data=data,
                           title=title,
                           page=page,
                           description=description)


@desa.route('/perantau/tandai-pulang/<int:id>')
@login_required
def TandaiPulang(id):
    """get email perantau"""
    perantau = CovidPerantau.query.filter_by(
        id=id, tujuan_desa=current_user.village_id).first()
    if perantau is None:
        flash('Data perantau tidak ditemukan', 'error')
    else:
        perantau.pulang()
        """Respond to new user's request to confirm their account."""
        get_queue().enqueue(
            send_email,
            recipient=perantau.email,
            subject='Pemberitahuan Kepulangan',
            template='account/email/perantau_pulang',
            # current_user is a LocalProxy, we want the underlying user object
            perantau=CovidPerantau.query.filter_by(
                id=id, tujuan_desa=current_user.village_id).first())
        flash(
            'Pemberitahuan kepulangan di kirim ke email {}.'.format(
                perantau.email), 'info')
    return redirect(url_for('desa.PerantauDataView'))


"""Edit Data Perantau"""
@desa.route('/perantau/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@required_roles('Desa')
def EditPerantau(id):
    title = "Edit Data Pemudik"
    page = "Edit Data"
    perantau = CovidPerantau.query.filter_by(
        id=id, tujuan_desa=current_user.village_id).first_or_404()
    if perantau.asal_negara is None or perantau.asal_negara == 'ID':
        form = CovidPerantauForm(obj=perantau)
        print(form.demam.data)
        if form.validate_on_submit():
            form.populate_obj(perantau)
            db.session.commit()
            flash('Data perantau berhasil diedit', 'success')
            return redirect(url_for('desa.PerantauDataView'))
    else:
        form = CovidPerantauLuarNegeriForm(obj=perantau)
        if form.validate_on_submit():
            form.populate_obj(perantau)
            db.session.commit()
            flash('Data perantau berhasil diedit', 'success')
            return redirect(url_for('desa.PerantauDataView'))
    return render_template('covid19/desa/perantau_edit.html',
                           perantau=perantau,
                           form=form,
                           title=title,
                           page=page)


"""Delete Data Perantau"""
@desa.route('/perantau/delete/<int:id>', methods=['GET', 'POST'])
@login_required
@required_roles('Desa')
def DeletePerantau(id):
    perantau = CovidPerantau.query.filter_by(
        id=id, tujuan_desa=current_user.village_id).first_or_404()
    db.session.delete(perantau)
    db.session.commit()
    flash('Data perantau {} berhasil dihapus'.format(perantau.full_name()),
          'error')
    return redirect(url_for('desa.PerantauDataView'))


@desa.route('/perantau/print/data')
@login_required
@required_roles('Desa')
def PerantauDataPrint():
    """View all Data Perantau mau mudik"""
    title = "Data Perantau"
    page = "Print Data"
    description = "Desa vs Corona"
    data = CovidPerantau.query.order_by(CovidPerantau.id.desc()).filter_by(
        tujuan_desa=current_user.village_id).all()
    return render_template('covid19/data/index.html',
                           data=data,
                           title=title,
                           page=page,
                           description=description)


@desa.route('/perantau/arrival-today/data')
@login_required
@required_roles('Desa')
def PerantauDataArrivalToday():
    """View all Data Perantau mau mudik"""
    today = datetime.today()
    title = "Data Perantau"
    page = "Kedatangan Hari Ini"
    description = "Desa vs Corona"
    data = CovidPerantau.query.filter_by(tujuan_desa=current_user.village_id,
                                         tgl_mudik=today).all()
    return render_template('covid19/data/index.html',
                           data=data,
                           title=title,
                           page=page,
                           description=description)


"""Covid19"""
@desa.route('/deteksi-sakit/view/data')
@login_required
@required_roles('Desa')
def DeteksiSakitDataView():
    """View all Data Deteksi Sakit"""
    title = "Data Deteksi Sakit"
    page = "View Data Deteksi Sakit"
    description = "Desa vs Corona"
    data = DeteksiSakit.query.order_by(
        DeteksiSakit.id.desc()).filter_by(desa=current_user.village_id).all()
    return render_template('covid19/data/deteksi_sakit.html',
                           data=data,
                           title=title,
                           page=page,
                           description=description)


@desa.route('/deteksi-sakit/ditangani/<int:id>')
@login_required
def TandaiSudahDitangani(id):
    """get email perantau"""
    sakit = DeteksiSakit.query.filter_by(id=id,
                                         desa=current_user.village_id).first()
    if sakit is None:
        flash('Data pelapot tidak ditemukan', 'error')
    else:
        sakit.sudah_ditangani()
        """Respond request to ditangani"""
        flash(
            'Laporan atas nama {} sudah ditangani !!!'.format(
                sakit.full_name()), 'success')
    return redirect(url_for('desa.DeteksiSakitDataView'))


@desa.route('/deteksi-sakit/print/data')
@login_required
@required_roles('Desa')
def DeteksiSakitDataPrint():
    """Print all Data Deteksi Sakit"""
    title = "Data Deteksi Sakit"
    page = "Print Data Deteksi Sakit"
    description = "Desa vs Corona"
    data = DeteksiSakit.query.order_by(
        DeteksiSakit.id.desc()).filter_by(desa=current_user.village_id).all()
    return render_template('covid19/data/deteksi_sakit.html',
                           data=data,
                           title=title,
                           page=page,
                           description=description)


@desa.route('/embed-code')
@login_required
@required_roles('Desa')
def EmbedCode():
    title = "Embed Statistik"
    description = "Kawal Mudik"
    form_kab = EmbedCodeKab()
    form_pemudik = EmbedCodePemudik()
    form_sakit = EmbedCodeOrangSakit()
    form_cari_pemudik = EmbedCodeSearchPemudik()
    return render_template('covid19/data/widget.html',
                           title=title,
                           description=description,
                           form_kab=form_kab,
                           form_pemudik=form_pemudik,
                           form_cari_pemudik=form_cari_pemudik,
                           form_sakit=form_sakit)


"""Generate Kode Statistik Covid-19 Kabupaten"""
@desa.route('/embed-code/kabupaten', methods=['GET', 'POST'])
@required_roles('Desa')
def EmbedCodeKabupaten():
    title = "Embed Statistik Covid19 Kabupaten"
    description = "Kawal Mudik"
    link = url_for('covid19.StatistikCoronaKabupaten',
                   _external=True,
                   _scheme='https')
    form_kab = EmbedCodeKab()
    form_kab.code.data = '<iframe width="1300" height="1780" \
        src="{}" \
        frameborder="0" gesture="media" allow="encrypted-media" \

app/templates/covid19/data/partials/data_perantau.html
            <div class="container">               
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box table-responsive">
                            <h4 class="m-t-0 header-title"><b>{{title}}</b></h4>
                            <p class="text-muted font-13 m-b-30">
                                {{ title }} {{ description }}
                            </p>
                            <!--start table-->
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>{{_('No')}}</th>
                                        <th>{{_('Nama Lengkap')}}</th>
                                        <th>{{_('NIK')}}</th>
                                        <th>{{_('Alamat Lengkap')}}</th>
                                        <th>{{_('Jenis Kelamin')}}</th>
                                        <th>{{_('No Telp')}}</th>
                                        <th>{{_('Asal Negara')}}</th>
                                        <th>{{_('Asal Provinsi')}}</th>
                                        <th>{{_('Asal Kabupaten')}}</th>
                                        <th>{{_('Tanggal Mudik')}}</th>
                                        <th>{{_('Kondisi')}}</th>
                                        <th>{{_('Aksi Data')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for u in data %}
                                    <tr>
                                        <td>{{ loop.index }}</td>
                                        <td>{{ u.first_name }} {% if u.last_name is not none %} {{ u.last_name }} {% endif %}</td>
                                        <td>{% if u.nik is not none %} {{ u.nik }} {% else %} {{_(' Tidak Terdata')}} {% endif %}</td>
                                        <td>{{ u.alamat }}</td>
                                        <td>
                                            {% if u.jk == '1' %}
                                            {{_('Laki-laki')}}
                                            {% elif u.jk == '2' %}
                                            {{_('Perempuan')}}
                                            {% else %}
                                            {{_('Tidak Terdata')}}
                                            {% endif %}
                                        </td>
                                        <td>{% if u.telp is not none %} {{ u.telp }} {% else %} {{_(' Tidak Terdata')}} {% endif %}</td>
                                        <td>
                                            {% if u.asal_negara is none %}
                                            {{_('Indonesia')}}
                                            {% else %}
                                            {{ u.perantau_luarnegeri.name }}
                                            {% endif %}
                                        </td>
                                        <td>{{ u.perantau_provinsi.name }}</td>
                                        <td>{{ u.perantau_kabupaten.name }}</td>
                                        <td>{{ u.tgl_mudik }}</td>
                                        <td>
                                        {% if (u.demam == false) and (u.batuk_pilek == false) and (u.sakit_tenggorokan == false) and (u.sesak_napas == false) %}
                                        {{_('Sehat')}}
                                        {% elif (u.demam == true) and (u.batuk_pilek == true) and (u.sakit_tenggorokan == true) and (u.sesak_napas == true) %}
                                        {{_('Sangat Buruk')}}
                                        {% else %}
                                        {{_('Kurang Sehat')}}
                                        {% endif %}
                                        </td>
                                        <td>
                                        {% if u.confirmed == true %}
                                        {% else %}
                                        <a href="{{ url_for('desa.TandaiPulang', id=u.id) }}"><span class="label label-primary">{{_('Tandai Pulang')}}</span></a>
                                        {% endif %}
                                        <a href="{{ url_for('desa.DeletePerantau', id=u.id) }}"><span class="label label-danger">{{_('Hapus')}}</span></a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <!--end table-->
                        </div>
                    </div>
                </div>
            </div>

app/templates/covid19/data/partials/data_sakit.html
            <div class="container">               
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box table-responsive">
                            <h4 class="m-t-0 header-title"><b>{{title}}</b></h4>
                            <p class="text-muted font-13 m-b-30">
                                {{ title }} {{ description }}
                            </p>
                            <!--start table-->
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>{{_('No')}}</th>
                                        <th>{{_('Nama Lengkap')}}</th>
                                        <th>{{_('Alamat Lengkap')}}</th>
                                        <th>{{_('Email')}}</th>
                                        <th>{{_('No Telp')}}</th>
                                        <th>{{_('Status')}}</th>
                                        <th>{{_('Aksi Data')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for u in data %}
                                    <tr>
                                        <td>{{ loop.index }}</td>
                                        <td>{{ u.full_name() }}</td>
                                        <td>{{ u.alamat }}</td>
                                        <td>{{ u.email }}</td>
                                        <td>{{ u.telp }}</td>
                                        <td>
                                            {% if u.confirmed == true %}
                                                {{_('Sudah ditangani')}}
                                            {% else %}
                                                {{_('Belum ditangani')}}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if u.confirmed == true %}
                                            {% else %}
                                            <a href="{{ url_for('desa.TandaiSudahDitangani', id=u.id) }}"><span class="label label-primary">{{_('Tandai sudah ditangani')}}</span></a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <!--end table-->
                        </div>
                    </div>
                </div>
            </div>

app/templates/covid19/data/partials/print_data_sakit.html
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                        <h4 class="m-t-0 header-title"><b>{{title}}</b></h4>
                        <p class="text-muted font-13 m-b-30">
                            {{ title }} {{ description }}
                        </p>
                        <!--start table-->
                        <table id="datatable-buttons" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>{{_('No')}}</th>
                                    <th>{{_('Nama Lengkap')}}</th>
                                    <th>{{_('Alamat Lengkap')}}</th>
                                    <th>{{_('Email')}}</th>
                                    <th>{{_('No Telp')}}</th>
                                    <th>{{_('Status')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for u in data %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>{{ u.full_name() }}</td>
                                    <td>{{ u.alamat }}</td>
                                    <td>{{ u.email }}</td>
                                    <td>{{ u.telp }}</td>
                                    <td>
                                        {% if u.confirmed == true %}
                                            {{_('Terkonfirmasi')}}
                                        {% else %}
                                            {{_('Belum dikonfirmasi')}}
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <!--end table-->
                    </div>
                </div>
            </div>

app/templates/covid19/data/partials/textbox_widget.html
    <div class="row">
        <div class="col-md-4">
            <div class="card-box">
                <h3 class="header-title m-t-0 m-b-30">{{('Statistik Informasi Covid-19 Kabupaten Pemalang')}}</h3>
                <form>
                {{ form_kab.hidden_tag() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    {{ form_kab.code(class="form-control") }}
                                    {% for error in form_kab.code.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <a href="{{ url_for('desa.EmbedCodeKabupaten') }}" class="btn btn-success waves-effect waves-light" role="button" aria-disabled="true">{{_('Dapatkan Code')}}</a>
                        </div>
                    </div>
                </div>
                </form>
            </div> <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-md-4">
            <div class="card-box">
            <h3 class="header-title m-t-0 m-b-30">{{('Statistik Pemudik Desa')}} {{ current_user.full_name() }}</h3>
                <form>
                {{ form_pemudik.hidden_tag() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    {{ form_pemudik.code(class="form-control") }}
                                    {% for error in form_pemudik.code.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <a href="{{ url_for('desa.EmbedCodePemudikDesa', village_id=current_user.village_id) }}" class="btn btn-success waves-effect waves-light" role="button" aria-disabled="true">{{_('Dapatkan Code')}}</a>
                        </div>
                    </div>
                </div>
                </form>
            </div> <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-md-4">
            <div class="card-box">
            <h3 class="header-title m-t-0 m-b-30">{{('Statistik Masyarakat Sakit Desa')}} {{ current_user.full_name() }}</h3>
               <form>
                {{ form_sakit.hidden_tag() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    {{ form_sakit.code(class="form-control") }}
                                    {% for error in form_sakit.code.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <a href="{{ url_for('desa.EmbedCodeSakitDesa', village_id=current_user.village_id) }}" class="btn btn-success waves-effect waves-light" role="button" aria-disabled="true">{{_('Dapatkan Code')}}</a>
                        </div>
                    </div>
                </div>
                </form>
            </div> <!-- end card -->
        </div>
        <!-- end col -->

    </div>
    <!-- end row -->

    <div class="row">
        <div class="col-md-4">
            <div class="card-box">
                <h3 class="header-title m-t-0 m-b-30">{{('Pencarian Data Pemudik Kabupaten Pemalang')}}</h3>
                <form>
                {{ form_kab.hidden_tag() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    {{ form_cari_pemudik.code(class="form-control") }}
                                    {% for error in form_cari_pemudik.code.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <a href="{{ url_for('desa.EmbedCodeSearchDataPemudik') }}" class="btn btn-success waves-effect waves-light" role="button" aria-disabled="true">{{_('Dapatkan Code')}}</a>
                        </div>
                    </div>
                </div>
                </form>
            </div> <!-- end card -->
        </div>
        <!-- end col -->

    </div>
    <!-- end row -->