app/maps/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import ValidationError
from wtforms.fields import (StringField, SubmitField, SelectField, DateField,
                            IntegerField)
from wtforms.fields.html5 import EmailField
from wtforms.validators import (Email, InputRequired, Length, DataRequired,
                                Optional)
from app.models import (Country, Provinces, Regencies, Districts, Villages,
                        DeteksiSakit)


class CovidPerantauForm(FlaskForm):
    first_name = StringField('Nama Depan',
                             validators=[InputRequired(),
                                         Length(1, 64)])
    last_name = StringField('Nama Belakang')
    nik = StringField('NIK', validators=[InputRequired()])
    tgl_lahir = DateField('Tanggal Lahir',
                          format='%Y/%m/%d',
                          validators=[Optional()])
    jk = SelectField('Jenis Kelamin ',
                     choices=[(0, '--Pilih Jenis Kelamin--'), (1, 'Laki-laki'),
                              (2, 'Perempuan')],
                     coerce=int)
    shdk = SelectField('Status Hubungan Dalam Keluarga',
                       choices=[(0, '--Pilih Salah Satu--'),
                                (1, 'Kepala Keluarga'), (2, 'Suami'),
                                (3, 'Istri'), (4, 'Anak'), (5, 'Menantu'),
                                (6, 'Cucu'), (7, 'Orang Tua'), (8, 'Mertua'),
                                (9, 'Famili Lain'), (10, 'Pembantu'),
                                (11, 'Lainnya')],
                       coerce=int)
    jml_ak_dan_pemudik = IntegerField('Jumlah Anggota Keluarga + Pemudik',
                                      validators=[InputRequired()],
                                      default=0)
    tujuan_kecamatan = SelectField('Kecamatan Tujuan:',
                                   validators=[DataRequired()],
                                   id='select_tujuankecamatan',
                                   coerce=int)
    tujuan_desa = SelectField('Desa/Kelurahan Tujuan:',
                              validators=[DataRequired()],
                              id='select_tujuandesa',
                              coerce=int)
    alamat = StringField(
        'Alamat Lengkap',
        validators=[InputRequired('Masukan Alamat !!'),
                    Length(1, 64)])
    email = EmailField('Email')
    telp = StringField('Nomor HP/Telp', validators=[InputRequired()])
    asal_provinsi = SelectField('Provinsi Asal:',
                                validators=[DataRequired()],
                                id='select_asalprovinsi',
                                coerce=int)
    asal_kabupaten = SelectField('Kabupaten Asal:',
                                 validators=[DataRequired()],
                                 id='select_asalkabupaten',
                                 coerce=int,
                                 default=0)
    alasan_mudik = SelectField('Alasan Mudik ',
                               choices=[
                                   (1, 'Kehilangan pekerjaan sementara/tetap'),
                                   (2, 'Usaha sepi/Bangkrut'),
                                   (3, 'Cuti Kerja/Liburan'), (4, 'Lainnya')
                               ],
                               coerce=int)
    alasan_mudik_lainnya = StringField('Alasan Mudik Lainnya')
    tgl_mudik = DateField('Tanggal Mudik',
                          format='%Y/%m/%d',
                          validators=[DataRequired('Masukan Mudik')])
    demam = SelectField('Demam',
                        choices=[(True, 'Ya'), (False, 'Tidak')],
                        default=False,
                        coerce=lambda x: x == 'True')
    batuk_pilek = SelectField('Batuk Pilek',
                              choices=[(True, 'Ya'), (False, 'Tidak')],
                              default=False,
                              coerce=lambda x: x == 'True')
    sakit_tenggorokan = SelectField('Sakit Tenggorokan ',
                                    choices=[(True, 'Ya'), (False, 'Tidak')],
                                    default=False,
                                    coerce=lambda x: x == 'True')
    sesak_napas = SelectField('Sesak Napas',
                              choices=[(True, 'Ya'), (False, 'Tidak')],
                              default=False,
                              coerce=lambda x: x == 'True')
    recaptcha = RecaptchaField()
    submit = SubmitField('Lapor Sekarang')

    def validate_nik(form, field):
        if len(field.data) != 16:
            raise ValidationError('Masukan NIK dengan benar')

    def validate_jk(form, field):
        if field.data == 0:
            raise ValidationError('Pilih Jenis Kelamin')

    def validate_shdk(form, field):
        if field.data == 0:
            raise ValidationError('Pilih SHDK')

    def __init__(self, *args, **kwargs):
        super(CovidPerantauForm, self).__init__(*args, **kwargs)
        self.asal_provinsi.choices = [
            (row.id, row.name)
            for row in Provinces.query.order_by('name').all()
        ]
        self.asal_kabupaten.choices = [
            (row.id, row.name) for row in Regencies.query.filter_by(
                province_id=Provinces.id).order_by('name').all()
        ]
        self.tujuan_kecamatan.choices = [
            (row.id, row.name) for row in Districts.query.filter_by(
                regency_id=Regencies.id).order_by('name').all()
        ]
        self.tujuan_desa.choices = [
            (row.id, row.name) for row in Villages.query.filter_by(
                district_id=Districts.id).order_by('name').all()
        ]


class CovidPerantauLuarNegeriForm(FlaskForm):
    first_name = StringField('Nama Depan',
                             validators=[InputRequired(),
                                         Length(1, 64)])
    last_name = StringField('Nama Belakang')
    nik = StringField('NIK', validators=[InputRequired()])
    tgl_lahir = DateField('Tanggal Lahir',
                          format='%Y/%m/%d',
                          validators=[Optional()])
    jk = SelectField('Jenis Kelamin ',
                     choices=[(0, '--Pilih Jenis Kelamin--'), (1, 'Laki-laki'),
                              (2, 'Perempuan')],
                     coerce=int)
    shdk = SelectField('Status Hubungan Dalam Keluarga',
                       choices=[(0, '--Pilih Salah Satu--'),
                                (1, 'Kepala Keluarga'), (2, 'Suami'),
                                (3, 'Istri'), (4, 'Anak'), (5, 'Menantu'),
                                (6, 'Cucu'), (7, 'Orang Tua'), (8, 'Mertua'),
                                (9, 'Famili Lain'), (10, 'Pembantu'),
                                (11, 'Lainnya')],
                       coerce=int)
    jml_ak_dan_pemudik = IntegerField('Jumlah Anggota Keluarga + Pemudik',
                                      validators=[InputRequired()],
                                      default=0)
    tujuan_kecamatan = SelectField('Kecamatan Tujuan:',
                                   validators=[DataRequired()],
                                   id='select_tujuankecamatan',
                                   coerce=int)
    tujuan_desa = SelectField('Desa/Kelurahan Tujuan:',
                              validators=[DataRequired()],
                              id='select_tujuandesa',
                              coerce=int)
    alamat = StringField(
        'Alamat Lengkap',
        validators=[InputRequired('Masukan Alamat !!'),
                    Length(1, 64)])
    email = EmailField('Email')
    telp = StringField('Nomor HP/Telp', validators=[InputRequired()])
    asal_negara = SelectField('Negara Asal:', validators=[DataRequired()])
    alasan_mudik = SelectField('Alasan Mudik ',
                               choices=[
                                   (1, 'Kehilangan pekerjaan sementara/tetap'),
                                   (2, 'Usaha sepi/Bangkrut'),
                                   (3, 'Cuti Kerja/Liburan'), (4, 'Lainnya')
                               ],
                               coerce=int)
    alasan_mudik_lainnya = StringField('Alasan Mudik Lainnya')
    tgl_mudik = DateField('Tanggal Mudik',
                          format='%Y/%m/%d',
                          validators=[DataRequired('Masukan Mudik')])
    demam = SelectField('Demam',
                        choices=[(True, 'Ya'), (False, 'Tidak')],
                        default=False,
                        coerce=lambda x: x == 'True')
    batuk_pilek = SelectField('Batuk Pilek',
                              choices=[(True, 'Ya'), (False, 'Tidak')],
                              default=False,
                              coerce=lambda x: x == 'True')
    sakit_tenggorokan = SelectField('Sakit Tenggorokan ',
                                    choices=[(True, 'Ya'), (False, 'Tidak')],
                                    default=False,
                                    coerce=lambda x: x == 'True')
    sesak_napas = SelectField('Sesak Napas',
                              choices=[(True, 'Ya'), (False, 'Tidak')],
                              default=False,
                              coerce=lambda x: x == 'True')
    recaptcha = RecaptchaField()
    submit = SubmitField('Lapor Sekarang')

    def validate_nik(form, field):
        if len(field.data) != 16:
            raise ValidationError('Masukan NIK dengan benar')

    def validate_jk(form, field):
        if field.data == 0:
            raise ValidationError('Pilih Jenis Kelamin')

    def validate_shdk(form, field):
        if field.data == 0:
            raise ValidationError('Pilih SHDK')

    def __init__(self, *args, **kwargs):
        super(CovidPerantauLuarNegeriForm, self).__init__(*args, **kwargs)
        self.asal_negara.choices = [
            (row.id, row.name) for row in Country.query.order_by('name').all()
        ]

app/maps/__init__.py
from app.maps.views import maps  # noqa

app/maps/views.py
from flask import (Blueprint, render_template, flash, redirect, url_for,
                   jsonify)
from sqlalchemy import func, and_
from flask_rq import get_queue

from app.models import (CovidPerantau, CovidDeteksiMandiri, DeteksiSakit,
                        Posko, RumahSakit, Puskesmas, DataODP, DataPDP,
                        DataPositif, Villages)
from app.schema import (covid_perantau_jumlah_per_desa_schema,
                        covid_perantau_schema)
from app import db
from app.email import send_email
from config import Config
from datetime import date

maps = Blueprint('maps', __name__)


@maps.route('/', methods=['GET', 'POST'])
def index():
    title = "MAPS"
    description = "Kawal Mudik"
    return render_template('maps/index.html',
                           title=title,
                           description=description)


@maps.route('/pemudik_per_desa', methods=['GET', 'POST'])
def pemudik_per_desa():
    desa = Villages.query.outerjoin(CovidPerantau).with_entities(
        Villages.id.label('desa_id'),
        func.count(CovidPerantau.tujuan_desa).label('pemudik')).group_by(
            Villages.id).all()
    result = covid_perantau_jumlah_per_desa_schema.dump(desa, many=True)
    return jsonify(result)


# @maps.route('/pemudik', methods=['GET', 'POST'])
# def pemudik():
#     desa = CovidPerantau.query.all()
#     result = covid_perantau_schema.dump(desa).data
#     return jsonify(result)

app/templates/maps/index.html
{% extends "core/homepage/core_template.html" %} {% block content %} {% include 'core/homepage/core_navbar.html' %}

<div class="wrapper">

    <div class="container">

        <!-- Start page tittle and breadcrumb -->
        {% include 'homepage/breadcrumb.html' %}
        <!-- end page title and breadcrumb -->

        {# Flash if user is aunteticated #} {% if (current_user.is_authenticated) %} {% with informations = get_flashed_messages(category_filter=["success_login"]) %} {% if informations %}
        <div class="alert alert-icon alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <i class="mdi mdi-information-outline"></i> {% for msg in informations %}
            <strong>{{ msg }} {{ current_user.full_name() }}, {{_('Anda login sebagai user')}}
                {{ current_user.get_role() }}</strong> {% endfor -%}
        </div>
        {% endif %} {% endwith %} {% endif %}

        <div id="map"></div>



    </div>
    <!-- end row -->
    <!--Footer-->
    {% include 'core/homepage/core_footer.html' %}
    <!--End Footer-->
</div>
</div>
{% endblock %} {% block customcss %}
<!-- Laeflet -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
<style>
    #map {
        width: 100%;
        height: 600px;
    }
    
    .info {
        padding: 6px 8px;
        font: 14px/16px Arial, Helvetica, sans-serif;
        background: white;
        background: rgba(255, 255, 255, 0.8);
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
        border-radius: 5px;
    }
    
    .info h4 {
        margin: 0 0 5px;
        color: #777;
    }
    
    .legend {
        text-align: left;
        line-height: 18px;
        color: #555;
    }
    
    .legend i {
        width: 18px;
        height: 18px;
        float: left;
        margin-right: 8px;
        opacity: 0.7;
    }
    
    @media only screen and (max-width:800px) {
        /* For tablets: */
        .legend {
            text-align: left;
            line-height: 18px;
        }
        .legend i {
            width: 18px;
            height: 18px;
            float: left;
            margin-right: 8px;
            opacity: 0.7;
        }
    }
    
    @media only screen and (max-width:500px) {
        /* For mobile phones: */
        .legend {
            text-align: left;
            line-height: 20px;
        }
        .legend i {
            width: 18px;
            height: 18px;
            float: left;
            margin-right: 8px;
            opacity: 0.7;
        }
    }
</style>
<script src="{{ url_for('static', filename='pemalang.min.js')}}"></script>
{% endblock %} {% block customjs %}
<!--Javascript Tombol Login-->

<!--End Javascript Tombol Login-->
<!--Counter up-->
<script src="{{ url_for('static', filename='plugins/waypoints/jquery.waypoints.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/counterup/jquery.counterup.min.js') }}"></script>

<!-- Laeflet -->

<script>
    var pemalangUpdate = pemalangData;
    $.ajax({
        type: "GET",
        url: '{{ url_for("maps.pemudik_per_desa") }}',
        datatype: "json",
        async: false,
        success: function(data) {
            data.forEach(function(value, i) {
                setPemudik(value.desa_id, value.pemudik);
            });
        }
    });


    function setPemudik(desa_id, pemudik) {
        for (var i = 0; i < pemalangUpdate.features.length; i++) {
            if (pemalangUpdate.features[i].properties.desa_id == desa_id) {
                pemalangUpdate.features[i].properties.pemudik = pemudik;
            }
        }
    }

    var map = L.map('map').setView([-7.0105213, 109.403589], 10);
    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        style: 'mapbox://styles/mapbox/light-v10',
        accessToken: 'pk.eyJ1IjoiYmFyYXJhbWFkaGFuIiwiYSI6ImNrOTd5dzF2bzBrY20zbXRhZG1sbTV5bXMifQ.xShg_s23saoVfSkIUe0Hqg'
    }).addTo(map);

    if (L.Browser.mobile) {
        map.dragging.disable();
        map.touchZoom.disable();
        if (map.tap) map.tap.disable();
        map.on('click', onTapToggleInteraction);
    }

    function onTapToggleInteraction(e) {

        if (!map.dragging.enabled()) {
            map.dragging.enable();
            map.touchZoom.enable();
            map.tap.enable();
        } else {
            map.dragging.disable();
            map.touchZoom.disable();
            map.tap.disable();
        }
    }

    // get color depending on population density value 
    function getColor(d) {
        return d > 1000 ? '#800026' :
            d > 500 ? '#BD0026' :
            d > 200 ? '#E31A1C' :
            d > 100 ? '#FC4E2A' :
            d > 50 ? '#FD8D3C' :
            d > 20 ? '#FEB24C' :
            d > 10 ? '#FED976' :
            d > 0 ? '#FFEDA0' :
            '#FFFFFF';
    }

    function style(feature) {
        return {
            weight: 2,
            opacity: 1,
            color: 'white',
            dashArray: '3',
            fillOpacity: 0.7,
            fillColor: getColor(feature.properties.pemudik)
        };
    }

    // control that shows state info on hover
    var info = L.control();

    info.onAdd = function(map) {
        this._div = L.DomUtil.create('div', 'info');
        this.update();
        return this._div;
    };

    info.update = function(props) {
        this._div.innerHTML = '<h4>Kabupaten Pemalang</h4>' + (props ?
            '<b>Desa : ' + props.NamaDesa + '</b><br />' + '<b>Kecamatan : ' + props.NamaKec + '</b><br />' + '<b>Pemudik : ' + props.pemudik + '</b>' :
            'Arahkan kursor ke suatu desa');
    };

    info.addTo(map);

    function onEachFeature(feature, layer) {
        layer.on({
            mouseover: highlightFeature,
            mouseout: resetHighlight,
            // click: zoomToFeature
        });
    }

    function highlightFeature(e) {
        var layer = e.target;

        layer.setStyle({
            weight: 5,
            color: '#666',
            dashArray: '',
            fillOpacity: 0.7
        });

        if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
            layer.bringToFront();
        }

        info.update(layer.feature.properties);
    }

    var geojson;

    function resetHighlight(e) {
        geojson.resetStyle(e.target);
        info.update();
    }

    function zoomToFeature(e) {
        map.fitBounds(e.target.getBounds());
    }

    function onEachFeature(feature, layer) {
        layer.on({
            mouseover: highlightFeature,
            mouseout: resetHighlight,
            click: zoomToFeature
        });
    }


    geojson = L.geoJson(pemalangUpdate, {
        style: style,
        onEachFeature: onEachFeature
    }).addTo(map);

    var legend = L.control({
        position: 'bottomright'
    });

    legend.onAdd = function(map) {

        var div = L.DomUtil.create('div', 'info legend'),
            grades = [0, 10, 20, 50, 100, 200, 500, 1000],
            labels = [],
            from, to;

        for (var i = 0; i < grades.length; i++) {
            from = grades[i];
            to = grades[i + 1];

            labels.push(
                '<i style="background:' + getColor(from + 1) + '"></i> ' +
                from + (to ? '&ndash;' + to : '+'));
        }

        div.innerHTML = labels.join('<br>');
        return div;
    };

    legend.addTo(map);
</script>
{% endblock %}